### ISSUE TITLE
Implement other output formats

### ISSUE THREAD

**Issue by jberkel** [PavloKapyshin/paka.cmark#2]
I need to perform some CommonMark cleaning from Python code and would like to parse and regenerate the markup with this libary.

This would require to add support for `FORMAT_COMMONMARK` (maybe others) to the code.
Happy to do this and submit a PR, but first wanted to check if that's something you would integrate (it kind of goes against the simple+lightweight tag line of the project).

**Comment by PavloKapyshin** [comment]
I’d name it `paka.cmark.to_commonmark`. Covering whole cmark API is an unstated (to avoid expectations) goal of this project, so go on, just make sure docs and tests are in place :)
